### ISSUE TITLE
Superclass mismatch for class Oauth2Token

### ISSUE THREAD

**Issue by canweriotnow** [pelle/oauth-plugin#144]
Generator provides model Oauth2Token as:

`class Oauth2Token < AccessToken`

But Oauth2Token is declared in /lib/oauth/models/consumers/services/oauth2_token.rb as:

`class Oauth2Token < ConsumerToken`,

resulting in:

```
13:45:05 worker.1 | superclass mismatch for class Oauth2Token
13:45:05 worker.1 | /Users/jason/estuary/sanderling/app/models/oauth2_token.rb:1:in `<top (required)>'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:423:in `load'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:423:in `block in load_file'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:615:in `new_constants_in'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:422:in `load_file'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:323:in `require_or_load'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:288:in `depend_on'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:206:in `require_dependency'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/railties-4.0.0/lib/rails/engine.rb:465:in `block (2 levels) in eager_load!'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/railties-4.0.0/lib/rails/engine.rb:464:in `each'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/railties-4.0.0/lib/rails/engine.rb:464:in `block in eager_load!'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/railties-4.0.0/lib/rails/engine.rb:462:in `each'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/railties-4.0.0/lib/rails/engine.rb:462:in `eager_load!'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/sidekiq-2.14.1/lib/sidekiq/cli.rb:199:in `boot_system'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/sidekiq-2.14.1/lib/sidekiq/cli.rb:42:in `parse'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/gems/sidekiq-2.14.1/bin/sidekiq:7:in `<top (required)>'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/bin/sidekiq:23:in `load'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/bin/sidekiq:23:in `<main>'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/bin/ruby_noexec_wrapper:14:in `eval'
13:45:05 worker.1 | /Users/jason/.rvm/gems/ruby-2.0.0-p247@sanderling/bin/ruby_noexec_wrapper:14:in `<main>'
13:45:05 worker.1 | exited with code 1
```

I'm assuming this is the cause. Any suggestions to rectify this?

**Comment by mremond** [comment]
I have the same trouble. Did you find an answer ?

**Comment by charusat09** [comment]
Me to facing similar error like :

```
Coverage may be inaccurate; Try setting JRUBY_OPTS="-Xcli.debug=true --debug"
superclass mismatch for class Shutdown
/home/mpatel/.rvm/gems/jruby-1.7.13/gems/torquebox-sidekiq-service-0.2.5/lib/torquebox-sidekiq-service.rb:3:in `Sidekiq'
/home/mpatel/.rvm/gems/jruby-1.7.13/gems/torquebox-sidekiq-service-0.2.5/lib/torquebox-sidekiq-service.rb:2:in `(root)'
org/jruby/RubyKernel.java:1065:in `require'
/home/mpatel/.rvm/gems/jruby-1.7.13/gems/bundler-1.10.4/lib/bundler/runtime.rb:1:in `(root)'
org/jruby/RubyArray.java:1613:in `each'
/home/mpatel/.rvm/gems/jruby-1.7.13/gems/bundler-1.10.4/lib/bundler/runtime.rb:76:in `require'
org/jruby/RubyArray.java:1613:in `each'

```
