### ISSUE TITLE
RecordNotFound is undefined

### ISSUE THREAD

**Issue by Dagnan** [pelle/oauth-plugin#20]
When I try to disconnect a user who is already disconnected from an oauth service I get the following:

uninitialized constant Oauth::Controllers::ConsumerController::RecordNotFound
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:440:in `load_missing_constant'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.8/lib/active_support/dependencies.rb:80:in`const_missing'
/myapp/vendor/plugins/oauth-plugin/lib/oauth/controllers/consumer_controller.rb:49:in `destroy'

**Comment by mahhek** [comment]
Any answer for this ? I am also facing same problem.

**Comment by tute** [comment]
Me too with v0.4.0.pre7.

**Comment by bournenapster** [comment]
i am also getting same any help rails 3 ?
