### ISSUE TITLE
Rails 2 can't find Railtie constant

### ISSUE THREAD

**Issue by nesquena** [pelle/oauth-plugin#45]
Following the instructions for **Rails 2.3.10** (although I am using Bundler in my rails 2 app):

```
# Gemfile
gem 'oauth', '~> 0.4.4'
gem "oauth-plugin", ">= 0.4.0.pre1"

$ bundle install
$ ./script/generate oauth_provider --test-unit --haml
```

Results in:

```
/Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-2.3.10/lib/active_support/dependencies.rb:466:in `load_missing_constant': uninitialized constant Rails::Railtie (NameError)
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/activesupport-2.3.10/lib/active_support/dependencies.rb:106:in `const_missing'
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/oauth-plugin-0.4.0.pre4/lib/oauth-plugin.rb:16
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/bundler-1.0.10/lib/bundler/runtime.rb:68:in `require'
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/bundler-1.0.10/lib/bundler/runtime.rb:68:in `require'
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/bundler-1.0.10/lib/bundler/runtime.rb:66:in `each'
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/bundler-1.0.10/lib/bundler/runtime.rb:66:in `require'
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/bundler-1.0.10/lib/bundler/runtime.rb:55:in `each'
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/bundler-1.0.10/lib/bundler/runtime.rb:55:in `require'
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/bundler-1.0.10/lib/bundler.rb:120:in `require'
    from /Users/nesquena/Documents/Development/Miso/miso-server/config/environment.rb:14
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/rails-2.3.10/lib/initializer.rb:111:in `run'
    from /Users/nesquena/Documents/Development/Miso/miso-server/config/environment.rb:10
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/rails-2.3.10/lib/commands/generate.rb:1:in `require'
    from /Users/nesquena/.rvm/gems/ree-1.8.7-2010.02/gems/rails-2.3.10/lib/commands/generate.rb:1
    from ./script/generate:3:in `require'
    from ./script/generate:3
```

Looks like the Railtie is defined even in Rails 2 where the definition doesn't make sense.

**Comment by Kimtaro** [comment]
Hey, see this pull request for a fix: https://github.com/pelle/oauth-plugin/issues#issue/36

**Comment by nesquena** [comment]
Ah yeah that is what I did in my local version. I assume this will be pulled in and committed soon. Thanks for the link. I will close my version of this issue since it is clearly a dup.
