### ISSUE TITLE
Validation failed - Client application can't be blank

### ISSUE THREAD

**Issue by robhorvath** [pelle/oauth-plugin#46]
I'm new to rails and ruby in general, but I may be running into an issue with the oauth-plugin itself.  I'm attempting to use the consumer portion of the logic to authorize my web app via a user's Twitter account.  Everything is setup to the point that I'm redirected to Twitter for the authorization, but when the user is redirected back to my app, I receive an error when the token is being saved into the MongoDB database:

`Mongoid::Errors::Validations in Oauth consumersController#callback`

`Validation failed - Client application can't be blank.`

It seems the Token model is expecting a "Client application" property to be populated, but I can't find this property anywhere.

One thing to note is I'm using the latest branch which includes fixes by 3en for mongoid, but the only way I can get the models to work is by using 'referenced_in' instead of 'embedded_in'.

What am I doing wrong here?  Thanks in advance.  -Rob

Application trace:

`app/models/consumer_token.rb:25:in `find_or_create_from_access_token'
app/controllers/oauth_consumers_controller.rb:16:in `callback'`

Partial full trace:

`vendor/ruby/1.8/gems/mongoid-2.0.0.rc.7/lib/mongoid/persistence.rb:234:in `fail_validate!'
vendor/ruby/1.8/gems/mongoid-2.0.0.rc.7/lib/mongoid/persistence.rb:75:in `save!'
vendor/ruby/1.8/gems/mongoid-2.0.0.rc.7/lib/mongoid/relations/referenced/many.rb:90:in `create!'
vendor/ruby/1.8/gems/simple_oauth-0.1.4/lib/simple_oauth/core_ext/object.rb:6:in `tap'
vendor/ruby/1.8/gems/mongoid-2.0.0.rc.7/lib/mongoid/relations/referenced/many.rb:89:in `create!'
app/models/consumer_token.rb:25:in `find_or_create_from_access_token'
vendor/ruby/1.8/bundler/gems/oauth-plugin-f805e8c359b1/lib/oauth/models/consumers/token.rb:38:in `find_or_create_from_request_token'
vendor/ruby/1.8/bundler/gems/oauth-plugin-f805e8c359b1/lib/oauth/controllers/consumer_controller.rb:35:in `callback'
app/controllers/oauth_consumers_controller.rb:16:in `callback'`

Edit: More info - after stepping into the framework code, I can see that the Token class is expecting a client_application_id to have a value.  I didn't think a consumer token needed to be associated with a client application?

**Comment by robhorvath** [comment]
It turns out I followed the docs incorrectly.  My User class was incorrectly referencing the wrong oauth class.  Starting from scratch with the setup fixed my issue.
