### ISSUE TITLE
Invalid OAuth request

### ISSUE THREAD

**Issue by andrey-kazakov** [pelle/oauth-plugin#47]
Hello and sorry for my English.
I am using oauth 0.4.4 and oauth-plugin 0.4.0.pre4 gems.
When i trying to access my app as an OAuth Provider
      8 consumer = OAuth::Consumer.new consumer_key, consumer_secret,
      9           :site => 'http://localhost:3000/', :scheme => :body
     10 
     11 request_token = consumer.get_request_token
consumer raises an exception
    /home/lain/.rvm/gems/ruby-1.9.2-p136/gems/oauth-0.4.4/lib/oauth/consumer.rb:217:in `token_request': 401 Unauthorized  (OAuth::Unauthorized)
        from /home/lain/.rvm/gems/ruby-1.9.2-p136/gems/oauth-0.4.4/lib/oauth/consumer.rb:139:in`get_request_token'
        from private/test_app.rb:11:in `<main>'

Rails log for this request is

<pre>Started POST "/oauth/request_token" for 127.0.0.1 at 2011-02-22 21:17:54 +0300
  Processing by OauthController#request_token as */*
  Parameters: {"oauth_body_hash"=>"2jmj7l5rSw0yVb/vlWAYkK/YBwk=", "oauth_callback"=>"oob", "oauth_consumer_key"=>"GAdP34UY4zunPwhm9hePODITteHxplQ3oShNPuKs", "oauth_signature_method"=>"HMAC-SHA1", "oauth_timestamp"=>"1298398673", "oauth_nonce"=>"aDRQijPyYJYODaqdZvpD2RMrReixMVcWb0zYSpjI", "oauth_version"=>"1.0", "oauth_signature"=>"0kYXwbPnNZK7JLpVVtnLs+H5klQ="}
Rendered text template (0.0ms)
Completed 401 Unauthorized in 10ms (Views: 2.7ms | ActiveRecord: 0.0ms)</pre>

When I trying to simulate this request using curl, I'm going to get

<pre>$ curl 'http://127.0.0.1:3000/oauth/request_token' -d 'oauth_body_hash=2jmj7l5rSw0yVb%2fvlWAYkK%2fYBwk%3d&oauth_callback=oob&oauth_consumer_key=GAdP34UY4zunPwhm9hePODITteHxplQ3oShNPuKs&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1298398673&oauth_nonce=aDRQijPyYJYODaqdZvpD2RMrReixMVcWb0zYSpjI&oauth_version=1.0&oauth_signature=0kYXwbPnNZK7JLpVVtnLs%2bH5klQ%3d' -v
* About to connect() to 127.0.0.1 port 3000 (#0)
*   Trying 127.0.0.1... connected
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> POST /oauth/request_token HTTP/1.1
> User-Agent: curl/7.19.7 (i486-pc-linux-gnu) libcurl/7.19.7 OpenSSL/0.9.8k zlib/1.2.3.3 libidn/1.15
> Host: 127.0.0.1:3000
> Accept: */*
> Content-Length: 309
> Content-Type: application/x-www-form-urlencoded
> 
&lt; HTTP/1.1 401 Unauthorized 
&lt; Access-Control-Allow-Origin: *
&lt; Content-Type: text/html; charset=utf-8
&lt; Cache-Control: no-cache
&lt; X-Ua-Compatible: IE=Edge
&lt; X-Runtime: 1.245471
&lt; Server: WEBrick/1.3.1 (Ruby/1.9.2/2010-12-25)
&lt; Date: Tue, 22 Feb 2011 23:57:49 GMT
&lt; Content-Length: 21
&lt; Connection: Keep-Alive
&lt; 
* Connection #0 to host 127.0.0.1 left intact
* Closing connection #0
Invalid OAuth Request</pre>

My database contains one ClientApplication
    ruby-1.9.2-p136 :001 > ClientApplication.all.to_a
     => [#<ClientApplication _id: 4d62f535e4279b2dec000001, created_at: 2011-02-21 23:28:53 UTC, updated_at: 2011-02-21 23:28:53 UTC, name: "...", url: "...", support_url: nil, callback_url: nil, key: "GAdP34UY4zunPwhm9hePODITteHxplQ3oShNPuKs", secret: "EQAD5fifIuC3qtAyrkIpqAEn39rK50Az55gxbVYD", user_id: nil>] 

I had tried many versions of oauth and oauth-plugin but I never got any successful result.
Two test consumers I had googled for `oauth test' show me the same:
http://term.ie/oauth/example/client.php
http://dev.k42b3.com/index.php/oauth/consumer

I'm using devise 1.2.rc but I have disabled it by <code>skip_before_filter :authenticate_user!</code> in both Application and Oauth controllers.

**Comment by harmsk** [comment]
I can confirm this bug. I'm using version 0.4.0.pre6, if you use version 0.3.11 then this will work just fine.

In provider_controller.rb this filter is set: oauthenticate :strategies => :two_legged, :interactive => false, :only => [:request_token]

Later the allow? method in application_controller_methods.rb is called, but based on the above filter it will always return false.

As far as I can see in this version of the plugin, as a provider, you cannot request a token and have the process complete successfully.
